In [1]:


import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import norm
from scipy import special
import pandas as pd



In [13]:
# Exercise 6.4 
#  The 19 nonmissing precipitation values in Table A.3. can be used to fit 
# the regression  Equation:
# ln(Precipitation +1mm) = 499.4 -0.512 p + 0.796 T

# THE MSE for this regression is 0.701. The constant 1mm has been
# added to ensure that logarithm is defined for all data values
# a. Estimate the missing precipitation value for 1956 using this eq
# b. Construct a 95% confidence interval for the estimated 1956 precipitation


# The missing precipitation value for 1956:

# Table A3: p= 1011.2 and T = 24.3

# Plug in these values in the regression equation

precip_1956 = np.exp(499.4-0.512*1011.2+0.796*24.3)-1

print('Missing precipitation from regression % .2f' % precip_1956 +' mm')




Missing precipitation from regression  1.74 mm


In [59]:
# b. Construct a 95% confidence interval for the estimated 
# 1956 precipitation with MSE 0.701

# uncertainty of y given x0 for regression:
# S^2 (y|x_0)= S_e^2/n+S_e^2*S^2_slope
# S^2_slope = (x_0-mean_x)^2/Sum_i(x_i-x_mean)^2

# The variance for the sampling distribution of the regression function
# or equivalently the variance of the conditional mean of the
# predictand given a particular predictor value x_0, is

# I use the simple approach, first co

# For multi regression with 2 predictors, then:

#vector_s^2(y|p_0,T_0) = S_e^2 * (vec_x_0)^T(X^T*X)^-1 *vec_x_0

# s_e^2=0.701
# 1956 vec_x_0 = (1011.2,24.3)
# X_matrix = [1 p_1 T_1, 1 p_2 T_2,...,p_1970 T_1970]

vec_p = ([1009.5,1010.9,1010.7,1011.2,1011.9,1011.2,1009.3,
        1011.1,1012,1011.4,1010.9,1011.5,1011,1011.2,1009.9,
        1012.5,1011.1,1011.8,1009.3,1010.6])
vec_T = ([26.1,24.5,24.8,24.5,24.1,24.3,26.4,24.9,23.7,23.5,24.0,
         24.1,23.7,24.3,26.6,24.6,24.8,24.4,26.8,25.2])

vec_p0T0 = np.array([1,1011.2,24.3])
vec_ones = np.ones(20)

print('vec_ones',vec_ones,len(vec_ones))
print('vec_p',vec_p,len(vec_p))
print('vec_T',vec_T,len(vec_T))
print('vec_p0T0',vec_p0T0)


matrix_X = np.array([vec_ones,vec_p,vec_T]).reshape(20,3)
print(matrix_X,matrix_X.shape)

vec_ones [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 20
vec_p [1009.5, 1010.9, 1010.7, 1011.2, 1011.9, 1011.2, 1009.3, 1011.1, 1012, 1011.4, 1010.9, 1011.5, 1011, 1011.2, 1009.9, 1012.5, 1011.1, 1011.8, 1009.3, 1010.6] 20
vec_T [26.1, 24.5, 24.8, 24.5, 24.1, 24.3, 26.4, 24.9, 23.7, 23.5, 24.0, 24.1, 23.7, 24.3, 26.6, 24.6, 24.8, 24.4, 26.8, 25.2] 20
vec_p0T0 [1.0000e+00 1.0112e+03 2.4300e+01]
[[1.0000e+00 1.0000e+00 1.0000e+00]
 [1.0000e+00 1.0000e+00 1.0000e+00]
 [1.0000e+00 1.0000e+00 1.0000e+00]
 [1.0000e+00 1.0000e+00 1.0000e+00]
 [1.0000e+00 1.0000e+00 1.0000e+00]
 [1.0000e+00 1.0000e+00 1.0000e+00]
 [1.0000e+00 1.0000e+00 1.0095e+03]
 [1.0109e+03 1.0107e+03 1.0112e+03]
 [1.0119e+03 1.0112e+03 1.0093e+03]
 [1.0111e+03 1.0120e+03 1.0114e+03]
 [1.0109e+03 1.0115e+03 1.0110e+03]
 [1.0112e+03 1.0099e+03 1.0125e+03]
 [1.0111e+03 1.0118e+03 1.0093e+03]
 [1.0106e+03 2.6100e+01 2.4500e+01]
 [2.4800e+01 2.4500e+01 2.4100e+01]
 [2.4300e+01 2.6400e+01 2.4900e+01]
 [2.3700e+

[[1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00
  1.0000e+00 1.0109e+03 1.0119e+03 1.0111e+03 1.0109e+03 1.0112e+03
  1.0111e+03 1.0106e+03 2.4800e+01 2.4300e+01 2.3700e+01 2.4100e+01
  2.6600e+01 2.4400e+01]
 [1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00
  1.0000e+00 1.0107e+03 1.0112e+03 1.0120e+03 1.0115e+03 1.0099e+03
  1.0118e+03 2.6100e+01 2.4500e+01 2.6400e+01 2.3500e+01 2.3700e+01
  2.4600e+01 2.6800e+01]
 [1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00
  1.0095e+03 1.0112e+03 1.0093e+03 1.0114e+03 1.0110e+03 1.0125e+03
  1.0093e+03 2.4500e+01 2.4100e+01 2.4900e+01 2.4000e+01 2.4300e+01
  2.4800e+01 2.5200e+01]]


In [48]:
#from numpy import matmul
matrix_X_T = np.transpose(matrix_X)
print('matrix_X_T',matrix_X_T)
print('Shape of transposed Matrix',matrix_X_T.shape)
matmul_X= np.matmul(matrix_X_T,matrix_X)
print('Shape of X_T*X',matmul_X.shape)

matrix_X_T [[1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00
  1.0000e+00 1.0109e+03 1.0119e+03 1.0111e+03 1.0109e+03 1.0112e+03
  1.0111e+03 1.0106e+03 2.4800e+01 2.4300e+01 2.3700e+01 2.4100e+01
  2.6600e+01 2.4400e+01]
 [1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00
  1.0000e+00 1.0107e+03 1.0112e+03 1.0120e+03 1.0115e+03 1.0099e+03
  1.0118e+03 2.6100e+01 2.4500e+01 2.6400e+01 2.3500e+01 2.3700e+01
  2.4600e+01 2.6800e+01]
 [1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00 1.0000e+00
  1.0095e+03 1.0112e+03 1.0093e+03 1.0114e+03 1.0110e+03 1.0125e+03
  1.0093e+03 2.4500e+01 2.4100e+01 2.4900e+01 2.4000e+01 2.4300e+01
  2.4800e+01 2.5200e+01]]
Shape of transposed Matrix (3, 20)
Shape of X_T*X (3, 3)


In [44]:
matmul_X.shape

(3, 3)

In [49]:
from numpy.linalg import inv

a = np.array([[1,2],[3,4]])
ainv = inv(a)

inv_X = inv(matmul_X)

inv_X.shape

(3, 3)

In [89]:
# multiply(): element-wise matrix multiplication - a#b? Dyadisch.
# matmul(): matrix product of two arrays - Matrix Produkt
# dot(): Dot product of two arrays - Skalar produkt

a = 2*np.ones((3))
b = np.ones((3))

print('multiply(a,b)',np.multiply(a,b))
print('matmul(a,b)',np.matmul(a,b))
print('dot(a,b)',np.dot(a,b))
#print(vec_p0T0.shape)
#print(inv_X.shape)

var_y_x0=matmul(inv_X,vec_p0T0)
(0.7**2*np.multiply(vec_p0T0,var_y_x0))

multiply(a,b) [2. 2. 2.]
matmul(a,b) 6.0
dot(a,b) 6.0


array([-5.13654114e-04,  1.08451656e+00, -1.15696383e-02])